/*
 * $Author: vadim.gritsenko $ $Date: 2002/11/19 04:00:16 $
 * $Revision: 1.4 $ $RCSfile: ErrorFrame.java,v $
 * Copyright of Equant.
 * ErrorFrame.java
 * Created on November 8, 2001, 2:02 PM
 * @author kpathuri
 * @version
 */
package com.equant.csi.client;

public class ErrorFrame extends javax.swing.JFrame {
    /** Creates new form ErrorFrame */
    public ErrorFrame() {
        initComponents();
        init();
    }

    public void init() {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception e) {
            //logger.error (e.toString (), e);
        }
        setSize(400, 325);
        this.setResizable(false);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        errorLab = new javax.swing.JLabel();
        errorCountLab = new javax.swing.JLabel();
        xmlScrollPane = new javax.swing.JScrollPane();
        xmlTextArea = new javax.swing.JTextArea();
        xmlLabel = new javax.swing.JLabel();

        getContentPane().setLayout(null);
        setTitle("Order Error Frame");
        setBackground(new java.awt.Color(172, 171, 198));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        errorLab.setText("Error Count:");
        errorLab.setForeground(java.awt.Color.red);
        errorLab.setBackground(java.awt.Color.white);
        errorLab.setFont(new java.awt.Font("Dialog", 1, 14));
        getContentPane().add(errorLab);
        errorLab.setBounds(40, 20, 100, 20);

        errorCountLab.setForeground(java.awt.Color.red);
        errorCountLab.setBackground(java.awt.Color.white);
        getContentPane().add(errorCountLab);
        errorCountLab.setBounds(140, 20, 220, 20);

        xmlScrollPane.setBorder(new javax.swing.border.MatteBorder(new java.awt.Insets(2, 2, 2, 2), java.awt.Color.orange));
        xmlScrollPane.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        xmlScrollPane.setBackground(java.awt.Color.white);
        xmlScrollPane.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        xmlScrollPane.setViewportView(xmlTextArea);

        getContentPane().add(xmlScrollPane);
        xmlScrollPane.setBounds(30, 70, 330, 190);

        xmlLabel.setText("Current Errors");
        xmlLabel.setForeground(java.awt.Color.black);
        xmlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(xmlLabel);
        xmlLabel.setBounds(30, 50, 330, 17);

        pack();

    }//GEN-END:initComponents
    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        // Add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /** Exit the Application */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new ErrorFrame().show();
    }

    public void setLabelText() {
        numClicks++;
        errorCountLab.setText(String.valueOf(numClicks));
    }

    public void setXml(String xml) {
        if (numClicks == 0)
            xmlTextArea.setText(xml);
        else
            xmlTextArea.append("\n" + xml);
    }

    private int numClicks = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLab;
    private javax.swing.JLabel errorCountLab;
    private javax.swing.JScrollPane xmlScrollPane;
    private javax.swing.JTextArea xmlTextArea;
    private javax.swing.JLabel xmlLabel;
    // End of variables declaration//GEN-END:variables

}

